"""Initial migration

Revision ID: e9da7c6778c9
Revises: 
Create Date: 2024-11-18 22:51:52.434544

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e9da7c6778c9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_vendor', sa.Boolean(), nullable=True),
    sa.Column('dob', sa.String(length=10), nullable=False),
    sa.Column('gender', sa.String(length=10), nullable=False),
    sa.Column('street', sa.String(length=255), nullable=False),
    sa.Column('city', sa.String(length=100), nullable=False),
    sa.Column('state', sa.String(length=100), nullable=False),
    sa.Column('zip', sa.String(length=20), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('bank_account_number', sa.String(length=50), nullable=False),
    sa.Column('bank_branch', sa.String(length=100), nullable=False),
    sa.Column('ifsc_code', sa.String(length=20), nullable=False),
    sa.Column('credit_card_number', sa.String(length=50), nullable=False),
    sa.Column('credit_card_expiry', sa.String(length=20), nullable=False),
    sa.Column('credit_card_cvv', sa.String(length=5), nullable=False),
    sa.Column('income', sa.String(length=50), nullable=False),
    sa.Column('order_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('purchase_date', sa.String(length=50), nullable=False),
    sa.Column('transaction_amount', sa.String(length=50), nullable=False),
    sa.Column('product_preferences', sa.Text(), nullable=False),
    sa.Column('communication_channels', sa.Text(), nullable=False),
    sa.Column('feedback_given', sa.Boolean(), nullable=False),
    sa.Column('customer_service_calls', sa.Integer(), nullable=False),
    sa.Column('complaints_raised', sa.Integer(), nullable=False),
    sa.Column('facebook_profile', sa.String(length=100), nullable=True),
    sa.Column('twitter_profile', sa.String(length=100), nullable=True),
    sa.Column('posts_liked', sa.Integer(), nullable=False),
    sa.Column('comments_posted', sa.Integer(), nullable=False),
    sa.Column('age_group', sa.String(length=50), nullable=False),
    sa.Column('marital_status', sa.String(length=50), nullable=False),
    sa.Column('occupation', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('locations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=255), nullable=True),
    sa.Column('link', sa.String(length=255), nullable=True),
    sa.Column('order', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('is_featured', sa.Boolean(), nullable=True),
    sa.Column('image', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.String(length=50), nullable=False),
    sa.Column('categories', sa.PickleType(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('imageSrc', sa.String(length=255), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('stars', sa.Integer(), nullable=False),
    sa.Column('rates', sa.Integer(), nullable=False),
    sa.Column('discount', sa.String(length=50), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('details', sa.String(length=500), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('services',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('service_type', sa.String(length=50), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=500), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.Column('image_url', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('reviews',
    sa.Column('review_id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('customer_id', sa.Integer(), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('review_text', sa.String(length=500), nullable=False),
    sa.Column('review_date', sa.Date(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('review_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('reviews')
    op.drop_table('services')
    op.drop_table('products')
    op.drop_table('locations')
    op.drop_table('customers')
    # ### end Alembic commands ###
